# -*- coding: utf-8 -*-

from marshmallow import Schema
from marshmallow.fields import Str


class EcstocopiaSchema(Schema):
    postura_atitude = Str()
    atitude_decubito = Str()
    iteracoes_exp_facial = Str()
    acies = Str()
    iteracoes_fala_linguagem = Str()
    biotipo = Str()
    estado_geral = Str()
    mov_involuntarios_descricao = Str()
    mov_involuntarios = Str()
    nivel_consciencia_lucidez = Str()
    nivel_consciencia_orientacao = Str()
    linfonodos_volume = Str()
    linfonodos_alteracoes_pele = Str()
    linfonodos_sensibilidade = Str()
    linfonodos_consistencia = Str()
    linfonodos_mobilidade = Str()
    linfonodos_tamanho = Str()
    linfonodos_localizacao = Str()
    linfonodos_adenomegalia = Str()
    linfonodos_dor = Str()
    linfonodos_descricao_dor = Str()
    linfonodos_quantidade = Str()
    linfonodos_textura = Str()
    tecido_celular_subcutaneo_espessura = Str()
    tecido_celular_subcutaneo_espasticidade = Str()
    tecido_celular_subcutaneo_flacidez = Str()
    mucosas_hidratacao = Str()
    mucosas_coloracao = Str()
    mucosas_lesoes = Str()
    estado_nutricional_estado = Str()
    estado_nutricional_quantidade = Str()
    perfusao_capilar_tipo = Str()
    perfusao_capilar_lentificada_tempo = Str()
    estado_hidratacao_tipo = Str()
    estado_hidratacao_quantificacao = Str()
    edema_detalhes_dor = Str()
    edema_dor = Str()
    edema_descricao_edema = Str()
    edema_detalhes_consistencia = Str()
    edema_intensidade = Str()
    edema_detalhes_intensidade = Str()
    edema_localizacao = Str()
    edema_detalhes_localizacao = Str()
    pele_coloracao = Str()
    pele_continuidade = Str()
    pele_umidade = Str()
    pele_textura = Str()
    pele_espessura = Str()
    pele_temperatura = Str()
    pele_elasticidade = Str()
    pele_mobilidade = Str()
    pele_turgor = Str()
    pele_sensibilidade = Str()
    pele_lesoes_elementares = Str()
    faneros_cabelos_tipos_implatacao = Str()
    faneros_cabelos_distribuicao = Str()
    faneros_cabelos_quantidade = Str()
    faneros_cabelos_coloracao = Str()
    faneros_cabelos_brilho = Str()
    faneros_unhas_formato = Str()
    faneros_unhas_cor = Str()
    faneros_unhas_resistencia = Str()
