# -*- coding: utf-8 -*-

from marshmallow import Schema
from marshmallow.fields import Str
from main.messages import MSG_FIELD_REQUIRED, MSG_ALREADY_EXISTS


class SintomasGeraisSchema(Schema):
    sintomas = Str()
    tempo = Str()
    sudoreses = Str()
    calafrios = Str()
    caibras = Str()
    quantidade = Str()
    alteracao_peso_presenca = Str()
    alteracao_peso_valor = Str()
    alteracao_peso_valor_peso = Str()
    alteracao_peso_tempo = Str()
    ouvidos_dor = Str()
    ouvidos_otorreia = Str()
    ouvido_otoragia = Str()
    ouvidos_zumbidos = Str()
    ouvidos_tontura = Str()
    olhos_dor_ocular = Str()
    olhos_prurido = Str()
    olhos_queimacao = Str()
    olhos_olho_seco = Str()
    olhos_perda_visao = Str()
    olhos_fotofobia = Str()
    olhos_vermelhidao = Str()
    faringe_dor_garganta = Str()
    faringe_disfagia = Str()
    faringe_tosse = Str()
    faringe_halitose = Str()
    faringe_pigarro = Str()
    faringe_ronco = Str()
    cavidade_bucal_silose = Str()
    cavidade_bucal_halitose = Str()
    cavidade_bucal_dor = Str()
    cavidade_bucal_ulceracoes = Str()
    nariz_prurido = Str()
    nariz_dor = Str()
    nariz_espirros = Str()
    nariz_obstrucao_nasal = Str()
    nariz_corrimento_nasal = Str()
    nariz_epistaxe = Str()
    nariz_dispneia = Str()
    nariz_diminuicao_olfato = Str()
    febre_presenca = Str()
    febre_valor = Str()
    febre_tempo = Str()
