# -*- coding: utf-8 -*-

from marshmallow import Schema
from marshmallow.fields import Str


class RespiratorioSchema(Schema):

    respiratorio_presencacicatriz_valor = Str()
    respiratorio_presencacicatriz_motivo = Str()
    respiratorio_palpacao_ftv_valor = Str()
    respiratorio_palpacao_ftv_localizacao = Str()
    respiratorio_palpacao_submacico_localizacao = Str()
    respiratorio_palpacao_submacico_valor =Str()
    respiratorio_palpacao_manobra_de_lasengue = Str()
    respiratorio_palpacao_manobra_de_ruault = Str()
    respiratorio_palpacao_percussao = Str()
    respiratorio_palpacao_localizacao_percussao = Str()
    respiratorio_papacao_som_pulmonar = Str()
    respiratorio_palpacao_timpanico = Str()
    respiratorio_palpacao_macico = Str()
    respiratorio_palpacao_presencadedor_localizacao = Str()
    respiratorio_palpacao_presencadedor_tipo_da_dor = Str()
    respiratorio_palpacao_presencadedor_frenquencia_da_dor = Str()
    respiratorio_palpacao_presencadedor_intensidade_da_dor = Str()
    respiratorio_palpacao_presencadedor_fatores_que_pioram_a_dor = Str()
    respiratorio_palpacao_presencadedor_dorirradia_valor = Str()
    respiratorio_palpacao_presencadedor_dorirradia_frequencia = Str()
    respiratorio_palpacao_presencadedor_intensidade = Str()
    respiratorio_auscultapulmonar_murmurio_vesicular_presente = Str()
    respiratorio_auscultapulmonar_murmurio_vesicular_sonoridade = Str()
    respiratorio_auscultapulmonar_auscultavoz_valor = Str()
    respiratorio_auscultapulmonar_auscultavoz_ressonancia_aumentada = Str()
    respiratorio_auscultapulmonar_murmuriovesicular_valor = Str()
    respiratorio_auscultapulmonar_murmuriovesicular_localizacao = Str()
    respiratorio_auscultapulmonar_roncos_valor = Str()
    respiratorio_auscultapulmonar_roncos_localizacao = Str()
    respiratorio_auscultapulmonar_atritopleural_valor = Str()
    respiratorio_auscultapulmonar_atritopleural_localizacao = Str()
    respiratorio_auscultapulmonar_sopro_valor = Str()
    respiratorio_auscultapulmonar_sopro_localizacao = Str()
    respiratorio_auscultapulmonar_estritorgrosso_valor = Str()
    respiratorio_auscultapulmonar_estritorgrosso_localizacao = Str()
    respiratorio_auscultapulmonar_estritorfino_valor = Str()
    respiratorio_auscultapulmonar_estritorfino_localizacao = Str()
    respiratorio_auscultapulmonar_estritor_valor = Str()
    respiratorio_auscultapulmonar_estritor_localizacao = Str()
    respiratorio_auscultapulmonar_sibilos_valor = Str()
    respiratorio_auscultapulmonar_sibilos_localizacao = Str()
